repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-ast
  - repo: https://github.com/crate-ci/typos
    rev: v1.21.0
    hooks:
      - id: typos
        args: []
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^src/app/
        types_or: [javascript, ts]
  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
      - id: csslint
  - repo: local
    hooks:
      - id: ng-lint
        name: ng lint
        entry: ng lint
        language: system
        types: [ts]
        pass_filenames: false
